baseurl = "http://euforever.com/"
languageCode = "en-us"
title = "EU Forever"
theme = "hugo-strata-theme"

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "EU Forever"
	description = "Ernie and Ursula Forever"

	# Enable Google Analytics by inserting your tracking code
	googleAnalytics = ""


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "000000-0.png"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**August 13, 2016**<br>Zion National Park<br>[Springdale, UT](https://www.google.com/maps/place/Springdale,+UT/data=!4m2!3m1!1s0x80ca8d360b511ef1:0xd9b264a5aeb7087a?sa=X&ved=0ahUKEwjcp_3v3YvMAhVFET4KHSZWBpgQ8gEIfzAO)"
		# The icons will be shown if you enter your username
		twitter = ""
		github = ""
		dribbble = ""
		facebook = ""

		copyright = [
		]


	[params.portfolio]
		title = "Where"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."
