baseurl = "http://euforever.com/"
languageCode = "en-us"
title = "EU Forever"
theme = "hugo-strata-theme"

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "EU Forever"
	description = "Ernie and Ursula Forever"

	# Enable Google Analytics by inserting your tracking code
	googleAnalytics = "UA-76572155-1"

